# bundle exec gulp --watch
# Sera - OnePage Jekyll Template
# Configuration File
#

# Information for compile
exclude: ["node_modules", "gulpfile.js", "package.json", "Gemfile", "README.md"]

#
# If your website is placed in a separate folder on your server please modify
# this with your folder name, by default is empty.
# Example: Sera Demo is hosted on projects.gleesik.ro/sera-onepage
# If I compile Sera Template and I put in /sera-onepage without modifing baseurl
# than scripts can't be loaded corectly.
# For this example my site url is: projects.gleesik.ro (This can be just www.example.com)
# My folder for Demo Website is: /sera-onepage so baseurl: /sera-onepage
#
baseurl:

# the base hostname & protocol for your site
url: "http://localhost:3000"

####################################
######   Optional Features    ######
####################################
smooth-scroll: false

####################################
###########   Plugins    ###########
####################################
plugins:
  - jekyll-archives # Sorry, not GitHub pages friendly!

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

#######################################################
#######################################################
###############   HEADER INFORMATIONS   ###############
#######################################################
#######################################################

# This is your site title
title: Peter Jefferys
# Website language
lang: en-US
# Header Title
header-title: tomorrow's <strong>Games</strong>
# Header Tagline
headter-tagline: Let's build

####################################
######   CTA Header Buttons   ######
####################################

# Focus Buttons
header-focus-button:
  title: Resume
  url: https://drive.google.com/file/d/1-liMXWR0aTtOn1Bf02A5Mma9kJq4oGvE/view

# Secondary Buttons
header-secondary-button:
  title: LinkedIn
  url: https://www.linkedin.com/in/peter-jefferys/

  linkedin: https://www.linkedin.com/in/peter-jefferys/

#
# This is your email adress, contact from send here all emails from contact section
# IMPORTANT: you can modify contact form from this static template, but now works contact form works with a free external server
# To configure this contact form, first please send a fictive email afeter you enter below your email and verify that :)
#
email: peter.b.jefferys@gmail.com

# Offer Banner Link
# Default link is a link to all Sera OnePage products
banner-link: https://drive.google.com/file/d/1-liMXWR0aTtOn1Bf02A5Mma9kJq4oGvE/view

####################################
######  Global Social Links   ######
####################################
youtube: '#'
pinterest: '#'
facebook: '#'
twitter: '#'
google-plus: '#'
vimeo: '#'

#########################
######   Widgets   ######
#########################

#
# About Blog Author Widget
#
about-widget:
  author-avatar: avatar-02.jpg
  author-name: Peter Jefferys
  author-tagline: Game Developer
  author-info: Cum sociis que penatibus et magnis dis parturient montes lorem, nascetur ridiculus mus. Donec quam felis, ultricies.
  author-social-links:
    youtube: '#'
    pinterest: '#'
    facebook: '#'
    twitter: '#'
    google-plus: '#'

# Google Map JS api
# This is my api for this template
key-api: AIzaSyDbnxVZQannH0GF4gtnnBFPiP9ofm2WqGs
map-text: Sera Google Map
map-text-location: Bucharest, Romania
map-lat: 44.4267674
map-lng: 26.102538399999958

# Enter your Mailchimp User ID and Campaign ID
# @TODO: Add in a link for where to find these
mailchimp:
  user-id: REPLACEME
  list-id: REPLACEME

####
#
# Hi you now use Sera - OnePage Jekyll Template created by Gleesik™
#
# Below are each section from the website in order from top to bottom
# @TODO Edit each sections with your real information and each section from Sera will autocomplete with your information
#
####

#####################################
#############   About   #############
#####################################
about-title: Hi I'm Peter Jefferys
about-description: I'm looking to break into the game development industry and apply what I have learned.  Videogames have always played a large part in my life growing up and now it's my turn to contribute.


#####################################
#############  Features  ############
#####################################
features-title: Features
features-description: FullSail University gave me the education and training I need to create and debug game engines and gameplay systems mainly in C++ and C#.

#
# Features
#
features:

# Feature
- title: Clean & Unique Design
  description: Maecenas sed laoreet urna. Praesent eget tristique tortor. Suspendisse consequat sed turpis in mattis.
  icon: pe-7s-vector

# Feature
- title: Professional Support
  description: Maecenas sed laoreet urna. Praesent eget tristique tortor. Suspendisse consequat sed turpis in mattis.
  icon: pe-7s-help2

# Feature
- title: Pixel Perfect
  description: Maecenas sed laoreet urna. Praesent eget tristique tortor. Suspendisse consequat sed turpis in mattis.
  icon: pe-7s-airplay


#####################################
############  Portfolio  ############
#####################################
portfolio-title: Portfolio
portfolio-description: Maecenas tempus nec mi et placerat. Duis at odio vitae ex gravida volutpat. Nulla finibus aliquet diam ut eleifend. Mauris consequat interdum quam. Mauris dui sapien, efficitur et cursus id, molestie fringilla turpis.

#
# Portfolio Grid
#
portfolio-categories: [Games, SideProjects, Websites, Other Work ]
portfolio:

# Portfolio Item
- title: D<span class="thin">eltaMind</span>
  categories: [Games, Development]
  image: deltamind.jpg
  url: '#'

# Portfolio Item
- title: A<span class="thin">ge of The Void</span>
  categories: [Games, Development]
  image: AoTV.jpg
  url: '#'

# Portfolio Item
- title: A<span class="thin">rduino GPS Project</span>
  categories: [SideProjects]
  image: AGPS.jpg
  url: 'https://github.com/FSPeterJ/GeoCacheProject'

# # Portfolio Item
# - title: F<span class="thin">irst Game</span>
#   categories: [Games]
#   image: First.jpg
#   url: '#'

# Portfolio Item
- title: A<span class="thin">ctive Controls Database</span>
  categories: [Development, Other Work]
  image: ACDB.jpg
  url: '#'

# Portfolio Item
- title: A<span class="thin">ctive Controls Website</span> 
  categories: [Development, Websites, Other Work]
  image: ACW.jpg
  url: 'http://www.activecontrols.com/'



#####################################
##########   Main Skills   ##########
#####################################
core-title: Skills
core-description: My bachelors in Game Development gave me the education and training I need to create and debug game engines and gameplay systems mainly in C++ and C#.


#
# Core Features Left
#
core-features-left:

# Feature
- name: C++
  description: My favorite programming language.  C++ 11 & 17
  icon: pe-7s-light

# # Feature
- name: Performance Profiling
  description: VS Performance profiler, Intel VTune
  icon: pe-7s-graph1

# Feature
- name: DirectX
  description: DX11 HLSL - Lighting, Geometry & Compute shaders
  icon: pe-7s-photo

# Feature
- name: Unity
  description: Game prototype projects & VRChat Avatars.
  icon: pe-7s-plugin

#
# Core Features Right
#
core-features-right:

# Feature
- name: Git
  description: Standard source control usage & recovery
  icon: pe-7s-cloud-upload

  # Feature
- name: Graphics Debugging
  description: VS Grahpics Debugger & Nvidia Nsight.
  icon: pe-7s-monitor

# Feature
- name: Teamwork
  description: Two team projects (Unity & C++ Custom)
  icon: pe-7s-users

# Feature
- name: Visual Studio 2017
  description: Your standard primary IDE experience
  icon: pe-7s-tools


#####################################
########### Testimonials ############
#####################################
# testimonials-title: Testimonials
# testimonials-description: Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi.

# #
# # Testimonials
# #
# testimonials:

# # Client
# - name: Johnatan Doe
#   url: http://themeforest.net
#   url-text: ThemeForest.net
#   avatar: avatar-01.jpg
#   cite: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius adipiscing lectus, eu ornare lectus semper in. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed.
#   logo-img: themeforest.png

# # Client
# - name: Adam Smith
#   url: http://codecanyon.net
#   url-text: CodeCanyon.net
#   avatar: avatar-02.jpg
#   cite: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius adipiscing lectus, eu ornare lectus semper in. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed.
#   logo-img: codecanyon.png

# # Client
# - name: Irene Warner
#   url: http://videohive.net
#   url-text: VideoHive.net
#   avatar: avatar-03.jpg
#   cite: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius adipiscing lectus, eu ornare lectus semper in. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed.
#   logo-img: videohive.png

# # Client
# - name: Richard Ryan
#   url: http://audiojungle.net
#   url-text: AudioJungle.net
#   avatar: avatar-04.jpg
#   cite: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius adipiscing lectus, eu ornare lectus semper in. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed.
#   logo-img: audiojungle.png


#####################################
############# Our Blog ##############
#####################################
blog-title: My Blog
blog-description: Just some fun or weird stuff I learned while working on different things.

#####################################
############### Team ################
#####################################
# team-title: Meet Our Team
# team-description: Nulla a tellus at turpis gravida congue non interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi. Nulla a tellus at turpis gravida congue non sed nisl. Pellentesque scelerisque eu neque et tincidunt.

# #
# # Team Members
# #
# team:

# # Team Member
# - name: Jack Skilton
#   tagline: Graphic Designer
#   avatar: avatar-01.jpg

#   # Social Links
#   youtube: '#'
#   pinterest: '#'
#   facebook: '#'
#   twitter: '#'
#   google-plus: '#'
#   vimeo: '#'

# # Team Member
# - name: James Young
#   tagline: Developer
#   avatar: avatar-02.jpg

#   # Social Links
#   youtube: '#'
#   pinterest: '#'
#   facebook: '#'
#   twitter: '#'
#   google-plus: '#'
#   vimeo: '#'

# # Team Member
# - name: Johnatan Doe
#   tagline: Hacker
#   avatar: avatar-04.jpg

#   # Social Links
#   youtube: '#'
#   pinterest: '#'
#   facebook: '#'
#   twitter: '#'
#   google-plus: '#'
#   vimeo: '#'

# # Team Member
# - name: Ecaterina Doe
#   tagline: Support Expert
#   avatar: avatar-03.jpg

#   # Social Links
#   youtube: '#'
#   pinterest: '#'
#   facebook: '#'
#   twitter: '#'
#   google-plus: '#'
#   vimeo: '#'


#####################################
########## Pricing Tables ###########
#####################################
# pricing-title: Pricing Tables
# pricing-description: Nulla a tellus at turpis gravida congue non interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi. Nulla a tellus at turpis gravida congue non sed nisl. Pellentesque scelerisque eu neque et tincidunt.

# #
# # Plan Personal
# #
# plan-personal-price: $99
# plan-personal-offer-1-title: 01 PSD Pack
# plan-personal-offer-1-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
# plan-personal-offer-2-title: 100 Support Tickets
# plan-personal-offer-2-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
# plan-personal-url: '#'

# #
# # Plan Business
# #
# plan-business-price: $499
# plan-business-offer-1-title: 05 PSD Pack
# plan-business-offer-1-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
# plan-business-offer-2-title: 1000 Support Tickets
# plan-business-offer-2-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
# plan-business-url: '#'

# #
# # Plan Ultimate
# #
# plan-ultimate-price: $999
# plan-ultimate-offer-1-title: 10 PSD Pack
# plan-ultimate-offer-1-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
# plan-ultimate-offer-2-title: Support Unlimited
# plan-ultimate-offer-2-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
# plan-ultimate-url: '#'


#####################################
############   Contact   ############
#####################################
contact-title: Contact Me
contact-description: I'd love to talk with you about any job opportunities.  Give me a call, email me or send a message through here.


#####################################
#############   Footer   ############
#####################################
# footer-description: Nulla a tellus at turpis gravida congue non interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat.
# footer-copyright-text: Gleesik&trade;
# footer-copyright-url: http://gleesik.ro/
footer-copyright-year: 2018

